# Generated by Django 4.2.8 on 2023-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
